/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appPageBRouteImport } from './routes/(app)/page-b'
import { Route as appPageARouteImport } from './routes/(app)/page-a'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appAdminRouteRouteImport } from './routes/(app)/admin/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appAdminUserManagementIndexRouteImport } from './routes/(app)/admin/user-management/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appPageBRoute = appPageBRouteImport.update({
  id: '/page-b',
  path: '/page-b',
  getParentRoute: () => appRouteRoute,
} as any)
const appPageARoute = appPageARouteImport.update({
  id: '/page-a',
  path: '/page-a',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRouteRoute = appAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminUserManagementIndexRoute =
  appAdminUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => appAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof appAdminRouteRouteWithChildren
  '/dashboard': typeof appDashboardRoute
  '/page-a': typeof appPageARoute
  '/page-b': typeof appPageBRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/about': typeof publicAboutRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/user-management': typeof appAdminUserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof appAdminRouteRouteWithChildren
  '/dashboard': typeof appDashboardRoute
  '/page-a': typeof appPageARoute
  '/page-b': typeof appPageBRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/about': typeof publicAboutRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/user-management': typeof appAdminUserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(app)/admin': typeof appAdminRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/page-a': typeof appPageARoute
  '/(app)/page-b': typeof appPageBRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/admin/user-management/': typeof appAdminUserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/dashboard'
    | '/page-a'
    | '/page-b'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/about'
    | '/'
    | '/api/auth/$'
    | '/admin/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/dashboard'
    | '/page-a'
    | '/page-b'
    | '/profile'
    | '/settings'
    | '/login'
    | '/signup'
    | '/about'
    | '/'
    | '/api/auth/$'
    | '/admin/user-management'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(public)'
    | '/(app)/admin'
    | '/(app)/dashboard'
    | '/(app)/page-a'
    | '/(app)/page-b'
    | '/(app)/profile'
    | '/(app)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(public)/about'
    | '/(public)/'
    | '/api/auth/$'
    | '/(app)/admin/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/page-b': {
      id: '/(app)/page-b'
      path: '/page-b'
      fullPath: '/page-b'
      preLoaderRoute: typeof appPageBRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/page-a': {
      id: '/(app)/page-a'
      path: '/page-a'
      fullPath: '/page-a'
      preLoaderRoute: typeof appPageARouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin': {
      id: '/(app)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAdminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/user-management/': {
      id: '/(app)/admin/user-management/'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof appAdminUserManagementIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
  }
}

interface appAdminRouteRouteChildren {
  appAdminUserManagementIndexRoute: typeof appAdminUserManagementIndexRoute
}

const appAdminRouteRouteChildren: appAdminRouteRouteChildren = {
  appAdminUserManagementIndexRoute: appAdminUserManagementIndexRoute,
}

const appAdminRouteRouteWithChildren = appAdminRouteRoute._addFileChildren(
  appAdminRouteRouteChildren,
)

interface appRouteRouteChildren {
  appAdminRouteRoute: typeof appAdminRouteRouteWithChildren
  appDashboardRoute: typeof appDashboardRoute
  appPageARoute: typeof appPageARoute
  appPageBRoute: typeof appPageBRoute
  appProfileRoute: typeof appProfileRoute
  appSettingsRoute: typeof appSettingsRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRouteRoute: appAdminRouteRouteWithChildren,
  appDashboardRoute: appDashboardRoute,
  appPageARoute: appPageARoute,
  appPageBRoute: appPageBRoute,
  appProfileRoute: appProfileRoute,
  appSettingsRoute: appSettingsRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
